server:
  port: 8080
  servlet:
    context-path: /feedback

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: student

  jpa:
    hibernate :
      ddl-auto: none
    show-sql: true
